bucket_name = "ENTER_YOUR_BUCKET_NAME_HERE"
cluster_name = "ENTER_YOUR_CLUSTER_NAME_HERE"
big_query_schema_name = "taxi_rides_dataset"
region = "asia-south2"
jars_file = "gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar"